apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: eks-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - image: vbuxe-dev
          name: wallet-service
          ports:
            - containerPort: 8080
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SENDGRID
              valueFrom:
                secretKeyRef:
                  name: send-grid-secret
                  key: SENDGRID
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-account-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_wallet_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-wallet-token-secret
                  key: TWILIO_wallet_TOKEN
            - name: PAYSTACK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paystack-secret-key
                  key: PAYSTACK_SECRET_KEY
            - name: PAYSTACK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: paystack-base-url
                  key: PAYSTACK_BASE_URL
          readinessProbe:
            httpGet:
              path: api/users/actuator/health
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: api/users/actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 200m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: wallet-service-config
      imagePullSecrets:
        - name: wallet-service-secret
        
        #
